# Site settings
title: future shadez
email: futureshadez@gmail.com
url: https://futureshadez.xyz
description: "future shadez is a digital art initiative utilising AI to generate images of a pop-tinted future."
keywords: "future shadez, nft, AI-generated"
skills:
meta_author: futureshadez
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
#disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 111111 #18bc9c #80B3FF
  primary-rgb: "17,17,17" #"24,288,156" #"128,179,255"
  secondary: 404040 #2c3e50 #FD6E8A
  secondary-dark: 7FFFD4 #233140 #A2122F

# Footer settings
footer:
  copyright: future shadez
#  location: Location
  social:
#  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/futureshadez
  - title: instagram
    url: https://instagram.com/futureshadeznft
  - title: facebook
    url: https://www.facebook.com/future-shadez-109020514897848
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Credits content
#credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a #href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
